---
title: "conexion mysql"
author: "Dario Quishpe"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R connection to Mysql

```{r}
install.packages("RMySQL")
library(RMySQL)
library(data.table)
library(readxl)
library(writexl)
```

```{r}
conn <- dbConnect(MySQL(), 
                  dbname = "repaso", 
                  host = "localhost", 
                  port = 3306,
                  user = "root", 
                  password = "dario1999")


```

```{r}
ventas <- dbGetQuery(conn, "SELECT * FROM ventas")
clientes <- dbGetQuery(conn, "SELECT * FROM clientes")
productos <- dbGetQuery(conn, "SELECT * FROM productos")
ventas<-as.data.table(ventas)
clientes<-as.data.table(clientes)
productos<- as.data.table(productos)
# Ver el resultado
head(ventas)
head(clientes)
head(productos)
```

```{r}
consolidada<-merge(ventas,
                   clientes[,.(ID_CLIENTE,Nombre)],
                   by="ID_CLIENTE",
                  all.x=TRUE
)

consolidada<-merge(consolidada,
                   productos[,.(ID_PRODUCTO,Nombre_Producto)],
                   by="ID_PRODUCTO",
                   all.x=TRUE
                   )

conso

```

```{r}
dbDisconnect(conn)
```



